# directory where uploaded photos are stored
photo.storage.dir=photos
aws.s3.bucket=imgshareapp-bucket-10002

#bind to all network interfaces to allow access from other devices
server.address=0.0.0.0
# server port optional
server.port=5001

# Maximum file size per upload
spring.servlet.multipart.max-file-size=15MB
# Maximum request size (all files combined)
spring.servlet.multipart.max-request-size=15MB


gallery.initial-load=30
gallery.page-load=20